consul-migrate: skip LDFLAGS QA check
We know that our gnuhash and LDFLAGS produce a functional binary, so we add ldflags
to the insane skip to avoid the following error:

   ERROR: consul-migrate-git-r0 do_package_qa: QA Issue: No GNU_HASH in the elf binary: 'consul-migrate/git-r0/packages-split/consul-migrate/usr/bin/consul-migrate' [ldflags]
   ERROR: consul-migrate-git-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
   ERROR: consul-migrate-git-r0 do_package_qa: Function failed: do_package_qa

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>